document.writeln("<div class=\"ztnytop\">");
document.writeln("	<div class=\"ztnycont\">");
document.writeln("		<a href=\"/\" target=\"_blank\" class=\"ztlogo\"><img src=\"/style/ztlogo.png\"></a>");
document.writeln("		<ul>");
document.writeln("			<li><a href=\"/\" target=\"_blank\">网站首页</a></li>");
document.writeln("<li><a href=\"/zt/xuefei/\" target=\"_blank\">学费标准</a></li>");
document.writeln("			<li><a href=\"/p/gaikuang/\" target=\"_blank\">学校简介</a></li>");
document.writeln("			<li><a href=\"/p/zhuanye/\" target=\"_blank\">专业设置</a></li>");
document.writeln("			<li><a href=\"/QQ.html\" target=\"_blank\">烹饪教师</a></li>");
document.writeln("			<li><a href=\"/p/zuopin/\" target=\"_blank\">学生作品</a></li>");
document.writeln("			<li><a href=\"/QQ.html\" target=\"_blank\">就业帮扶</a></li>");
document.writeln("			<li><a href=\"/p/huanjing/\" target=\"_blank\">校园环境</a></li>");
document.writeln("			<li><a href=\"/p/ruxue/\" target=\"_blank\">入学须知</a></li>");
document.writeln("			<li><a href=\"/p/baoming/\" target=\"_blank\">在线报名</a></li>");

document.writeln("			<div class=\"clear\"></div>");
document.writeln("		</ul>");
document.writeln("		<div class=\"clear\"></div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<style>");
document.writeln("	.ztnytop {");
document.writeln("	box-sizing:content-box;");
document.writeln("	width:100%;");
document.writeln("	background-color:#ffffff;	");
document.writeln("	padding:8px 0;");
document.writeln("	height:60px;");
document.writeln("}");
document.writeln(".ztnytop .ztnycont {");
document.writeln("	width:1216px;	margin:0 auto");
document.writeln("}");
document.writeln(".ztnytop a.ztlogo {");
document.writeln("  float: left;");
document.writeln("}");
document.writeln(".ztnytop .ztnycont ul {");
document.writeln("  width: 861px;");
document.writeln("  float: right;");
document.writeln("}");
document.writeln(".ztnytop .ztnycont li {");
document.writeln("  float: left;");
document.writeln("  width: 10%;");
document.writeln("  text-align: center;");
document.writeln("  line-height:59px;");
document.writeln("}");
document.writeln(".ztnytop .ztnycont li a {");
document.writeln("  color: #333333;");
document.writeln("  font-size: 17px;");
document.writeln("}");
document.writeln(".ztnytop .ztnycont li a:hover {");
document.writeln("	color: #E67015;	");
document.writeln("}");
document.writeln("</style>");
document.writeln("<script language=\"javascript\" src=\"//scripts.easyliao.com/js/easyliao.js\"></script>");